# Strategy Configs:
# Scheduling Parameters
SCHEDULE_EXECUTION_INTERVAL_IN_MINUTES = .5
SCHEDULE_EXECUTION_INTERVAL_IN_SECONDS = SCHEDULE_EXECUTION_INTERVAL_IN_MINUTES * 60
SCHEDULE_SLEEP_INTERVAL_IN_SECONDS = 1

# Trading
TRADING_SOURCE_CURRENCY_SYMBOL = "USD"
TRADING_UNIT_AMOUNT = 100

# Pricing Criteria
PRICE_TRENDS_SIZE = 10
PRICE_TRENDS_MIN_CONSECUTIVE_ITEMS = 3
PRICE_TRENDS_DOWNTREND_PERCENTAGE_THRESHOLD = -0.5
MIN_PERCENTAGE_GAIN_TO_BUY = .01
TAKE_PROFIT_PERCENTAGE_GAIN = 15
STOP_LOSS_PERCENTAGE = -1

strategyConfigs = {}
strategyConfigs["TRADING_SOURCE_CURRENCY_SYMBOL"] = TRADING_SOURCE_CURRENCY_SYMBOL
strategyConfigs["TRADING_UNIT_AMOUNT"] = TRADING_UNIT_AMOUNT
strategyConfigs["PRICE_TRENDS_SIZE"] = PRICE_TRENDS_SIZE
strategyConfigs["PRICE_TRENDS_MIN_CONSECUTIVE_ITEMS"] = PRICE_TRENDS_MIN_CONSECUTIVE_ITEMS
strategyConfigs["PRICE_TRENDS_DOWNTREND_PERCENTAGE_THRESHOLD"] = PRICE_TRENDS_DOWNTREND_PERCENTAGE_THRESHOLD
strategyConfigs["MIN_PERCENTAGE_GAIN_TO_BUY"] = MIN_PERCENTAGE_GAIN_TO_BUY
strategyConfigs["TAKE_PROFIT_PERCENTAGE_GAIN"] = TAKE_PROFIT_PERCENTAGE_GAIN
strategyConfigs["STOP_LOSS_PERCENTAGE"] = STOP_LOSS_PERCENTAGE

def getStrategyConfigs():
    return strategyConfigs